apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xjyc68tk5-python
  janus-idp.io/tekton: xjyc68tk5-python
  backstage.io/kubernetes-id: xjyc68tk5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xjyc68tk5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
